In [1]:
import numpy as np
import pandas as pd
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.model_selection import train_test_split
from sklearn.pipeline import make_pipeline
from tpot.builtins import ZeroCount
import pickle

In [2]:
x_data = pd.read_csv('x_data.csv')
y_data = pd.read_csv('y_data.csv')

del x_data['date']
del x_data['product_no']

tmp_y_data = np.array(y_data)
x_data = np.array(x_data)
y_data = tmp_y_data.flatten()

In [3]:
X_train, X_test, y_train, y_test = train_test_split(x_data, y_data, train_size=0.75, test_size=0.25, random_state=42)

In [4]:
with open('model/cafe24_train_model.txt', 'r') as f:
    model = pickle.load(f)



In [5]:
# predict
model.predict(X_test)


array([0, 1, 1, ..., 0, 1, 1])

In [6]:
# predict_proba
model.predict_proba(X_test)

array([[0.63447088, 0.36552912],
       [0.17688068, 0.82311932],
       [0.03202602, 0.96797398],
       ...,
       [0.71425971, 0.28574029],
       [0.12782532, 0.87217468],
       [0.43934005, 0.56065995]])

In [9]:
# predict_proba
real_testing = X_test[0:1]
model.predict_proba(real_testing)

array([[0.63447088, 0.36552912]])