In [1]:
from sklearn.preprocessing import Normalizer
from sklearn.preprocessing import RobustScaler
from sklearn.preprocessing import MinMaxScaler

from sklearn.model_selection import train_test_split

from sklearn.preprocessing import StandardScaler

from sklearn.neural_network import MLPClassifier

import numpy as np
import pandas as pd
import pickle

In [2]:
x_data = pd.read_csv('x_data.csv')
y_data = pd.read_csv('y_data.csv')

del x_data['date']
del x_data['product_no']

tmp_y_data = np.array(y_data)
x_data = np.array(x_data)
y_data = tmp_y_data.flatten()

print('x_data shape : ', x_data.shape)
print('y_data shape : ', y_data.shape)


('x_data shape : ', (293724, 17))
('y_data shape : ', (293724,))


In [3]:
X_train, X_test, y_train, y_test = train_test_split(x_data, y_data, train_size=0.75, test_size=0.25)
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(220293, 17)
(73431, 17)
(220293,)
(73431,)


In [5]:
with open('mlp_model/cafe24_mlp_train_model.txt', 'r') as f:
    model = pickle.load(f)



In [6]:
from sklearn.metrics import classification_report,confusion_matrix

# predict
predictions = model.predict(X_test)
print(confusion_matrix(y_test,predictions))

[[35568  5613]
 [11286 20964]]


In [7]:
# predict_proba
model.predict_proba(X_test)
print(classification_report(y_test,predictions))

             precision    recall  f1-score   support

          0       0.76      0.86      0.81     41181
          1       0.79      0.65      0.71     32250

avg / total       0.77      0.77      0.77     73431



In [8]:
# predict_proba
real_testing = X_test[0:1]
model.predict_proba(real_testing)
from sklearn.metrics import f1_score
print(f1_score(y_test, predictions, average='micro'))

0.7698655881031172


In [9]:
report = classification_report(y_test,predictions)

In [10]:
print(report)

             precision    recall  f1-score   support

          0       0.76      0.86      0.81     41181
          1       0.79      0.65      0.71     32250

avg / total       0.77      0.77      0.77     73431



In [20]:
report[:]

u'             precision    recall  f1-score   support\n\n          0       0.76      0.86      0.81     41181\n          1       0.79      0.65      0.71     32250\n\navg / total       0.77      0.77      0.77     73431\n'

In [21]:
print(len(report))

214


In [24]:
print(report[13])

p


In [34]:
a = report.split('\n')
for b in a:
    c = b.split()
print(a)
print(a[0])

[u'             precision    recall  f1-score   support', u'', u'          0       0.76      0.86      0.81     41181', u'          1       0.79      0.65      0.71     32250', u'', u'avg / total       0.77      0.77      0.77     73431', u'']
             precision    recall  f1-score   support


In [32]:
print(len(a))

7


In [35]:
print(c)

[]


In [36]:
a = report.split()

In [37]:
print(a)

[u'precision', u'recall', u'f1-score', u'support', u'0', u'0.76', u'0.86', u'0.81', u'41181', u'1', u'0.79', u'0.65', u'0.71', u'32250', u'avg', u'/', u'total', u'0.77', u'0.77', u'0.77', u'73431']


In [40]:
print(a[-4:-1])

[u'0.77', u'0.77', u'0.77']


In [45]:
from sklearn.metrics import f1_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import accuracy_score

print(f1_score(y_test, predictions, average='micro'))
print(precision_score(y_test, predictions, average='micro'))
print(recall_score(y_test, predictions, average='micro'))
print(accuracy_score(y_test, predictions))

0.7698655881031172
0.7698655881031172
0.7698655881031172
0.7698655881031172


In [50]:
print(y_test)
print(predictions)
print(len(y_test))

[1 0 1 ... 1 0 1]
[0 0 1 ... 1 0 0]
73431


In [61]:
ac = 0
for i in range(len(y_test)):
    #print(y_test[i], predictions[i])
    
    if y_test[i] == predictions[i]:
        #print('ac')
        ac += 1
        
    
        
print(ac)
print(len(y_test))
print(float(ac) / float(len(y_test)))

56532
73431
0.769865588103


In [70]:
TP = np.count_nonzero(y_test * predictions)
TN = np.count_nonzero((y_test - 1)*(predictions - 1))
FP = np.count_nonzero((y_test - 1)*predictions)
FN = np.count_nonzero(y_test*(predictions - 1))

In [71]:
print(TP)
print(TN)
print(FP)
print(FN)

20964
35568
5613
11286


In [75]:
precision_ = float(TP) / float(TP + FP)
recall_ = float(TP) / float(TP + FN)
f1_ = (2 * precision_ * recall_) / (precision_ + recall_)
print(precision_)
print(recall_)
print(f1_)

0.788802347895
0.650046511628
0.712733948697
