In [1]:
from sklearn.ensemble import BaggingClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.cross_validation import train_test_split
import numpy as np
import pandas as pd
import pickle

/home/notebook/jhko01/AIMD_PLATFORM/lib/python2.7/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [2]:
x_data = pd.read_csv('x_data.csv')
y_data = pd.read_csv('y_data.csv')

del x_data['date']
del x_data['product_no']

tmp_y_data = np.array(y_data)
x_data = np.array(x_data)
y_data = tmp_y_data.flatten()

In [3]:
X_train, X_test, y_train, y_test = train_test_split(x_data, y_data, train_size=0.75, test_size=0.25, random_state=42)

In [4]:
with open('model/cafe24_bagging_train_model.txt', 'r') as f:
    model = pickle.load(f)



In [5]:
# predict
model.predict(X_test)

array([0, 1, 1, ..., 0, 1, 0])

In [6]:
# predict_proba
model.predict_proba(X_test)

array([[0.74, 0.26],
       [0.36, 0.64],
       [0.1 , 0.9 ],
       ...,
       [0.82, 0.18],
       [0.2 , 0.8 ],
       [0.56, 0.44]])

In [7]:
# predict_proba
real_testing = X_test[0:1]
model.predict_proba(real_testing)

array([[0.74, 0.26]])